name: Python virtualenv
description: Set up a Python virtual environment with caching
inputs:
  python-version:
    description: The Python version to use
    required: true
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup env
      shell: bash
      run: |
        uv pip install --system --break-system-packages -e .[dev]

    - name: Show environment info
      shell: bash
      run: |
        # Show environment info.
        echo "✓ Installed $(python --version) virtual environment to $(which python)"
        pip freeze
